name: Docker
on: push

jobs:
  test-docker:
    runs-on: ubuntu-latest
    container:
      image: node:26-alpine3.23
      env:
        NODE_ENV: develpment
      ports:
        - 80
    steps:
      - name: node vertion
        run: node -v
      - name: test custome action
        uses: ./.github/actions/some-test-module
