name: First Workflow
on: [push]

jobs:
  run-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display some text # ← 8 пробілів перед "-"
        run: echo "Hello, world!" # ← 10 пробілів перед "run"
