name: First Workflow
on: [push]

jobs:
  run-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Command in terminal
        run: |
          echo "Check node version"
          node -v
          npm -v
