name: First work
on: [push]

jobs:
  first:
    strategy:
      matrix:
        node-version: [12, 14, 18]
        some-text: ["test", "hhhh", "ggg"]
      fail-fast: false
      max-parallel: 2
    runs-on: ubuntu-latest
    steps:
      - run: |
          node -v
          echo ${{matrix.some-text}}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: node -v
