name: Seventh Workflow
on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the title
        type: string
        required: true
        default: "Hello world"

jobs:
  run-seventh-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REPOSITORY_OWNER
          echo ${{ github.event.inputs.titleCustom }}
