name: Third Workflow
on: [push]

jobs:
  run-third-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List files and cope repo
        run: ls -a
      - uses: actions/checkout@v4
      - name: List files
        run: ls -a
